#Script to update VTY access lists on IOS

#Program Task Steps:

#1 Delete current VTY ACL and generate a new ACL
#2 Populate new ACL with desired IP ranges
#3 Enable VTY on devices
#$ Write Memory


#1
---
- name: Update VTY Access List against group (Loop)
  hosts: {{group}}
  gather_facts: false

  tasks:
    - name: Delete current VTY access List and create a new one
      ios_config:
        lines:
          - no ip access-list standard ACL-LIST
          - ip access-list standard ACL-LIST

#2
    - name: Configure VTY Access List IP addresses
      ios_config:
        lines:
          - remark NetworkMgmt
          - permit 10.0.0.0 0.0.0.255
          - remakr Ansible Tower
          - permit 10.100.0.1
          - deny any log
      parents: ip access-list standard ACL-LIST

#3
    - name: Enable VTY
      ios_config:
        lines:
          - line vty 0 15
          - access-class ACL-LIST

#4
    - name: Write mem
      ios_config:
        lines:
          - exit
          - write memory